version: "3"

services:
  terraform:
    image: hashicorp/terraform:0.12.24
    volumes:
      - ./:/workdir
    working_dir: "/workdir/dev"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
